volumes:
  rustfs_data:
  azurite-data:

services:
  rustfs:
    container_name: icechunk_rustfs
    image: rustfs/rustfs:1.0.0-alpha.83
    hostname: rustfs
    healthcheck:
      test: curl 127.0.0.1:9000/health
      interval: 1s
      retries: 30
    entrypoint: |
        /bin/sh -c '
        for bucket in testbucket
        do
          echo creating bucket "$$bucket";
          mkdir -p /data/"$$bucket"
        done;

        rustfs --access-key minio123 --secret-key minio123 --console-enable /data
        '
    volumes:
      - rustfs_data:/data
    ports:
      - '9000:9000'
      - '9001:9001'

  rustfs_init:
    container_name: icechunk_rustfs_init
    image: rustfs/rc:v0.1.3
    restart: "no"
    depends_on:
      rustfs:
        condition: service_healthy
        restart: true
    entrypoint:
      - /bin/sh
      - '-c'
      - |
        set -ex

        rc alias set local http://rustfs:9000 minio123 minio123
        rc admin user add local readonly basicuser
        rc admin user add local modify modifydata

        apk add --no-cache aws-cli
        export AWS_ACCESS_KEY_ID=minio123
        export AWS_SECRET_ACCESS_KEY=minio123

        echo '{
          "Version": "2012-10-17",
          "Statement": [
            {
              "Sid": "AllowGetObjectOnly",
              "Effect": "Allow",
              "Principal": { "AWS": ["readonly"] },
              "Action": [
                "s3:GetObject"
              ],
              "Resource": [
                "arn:aws:s3:::testbucket",
                "arn:aws:s3:::testbucket/*"
              ]
            },
            {
              "Sid": "AllowToModify",
              "Effect": "Allow",
              "Principal": { "AWS": ["modify"] },
              "Action": [
                "s3:GetObject",
                "s3:PutObject",
                "s3:DeleteObject",
                "s3:ListBucket"
              ],
              "Resource": [
                "arn:aws:s3:::testbucket",
                "arn:aws:s3:::testbucket/*"
              ]
            }
          ]
        }' >> policy.json
        cat policy.json

        aws --endpoint-url http://rustfs:9000 s3api put-bucket-policy \
          --bucket testbucket \
          --policy file://policy.json

        aws --endpoint-url http://rustfs:9000 s3api get-bucket-policy \
          --bucket testbucket

        exit 0

  toxiproxy:
    container_name: icechunk_toxiproxy
    image: ghcr.io/shopify/toxiproxy
    ports:
      - '8474:8474'
      - '9002:9002'

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite:3.33.0
    container_name: azurite
    hostname: azurite
    healthcheck:
      test: nc 127.0.0.1 10000 -z
      interval: 1s
      retries: 30
    command: azurite --silent --blobHost 0.0.0.0 --queueHost 0.0.0.0 --tableHost 0.0.0.0 -l /workspace
    ports:
      - "10000:10000" # Blob
      - "10001:10001" # Queue
      - "10002:10002" # Table
    volumes:
      - azurite-data:/workspace

  azurite-init:
    image: mcr.microsoft.com/azure-storage/azurite:3.33.0
    container_name: azurite_init
    restart: "no"
    depends_on:
      azurite:
        condition: service_healthy
        restart: true
    entrypoint: |
        /bin/sh -c '
        apk add --no-cache curl
        for _ in {1..10}; do
            if curl --silent --fail -XPUT "http://azurite:10000/devstoreaccount1/testcontainer?sv=2023-01-03&ss=btqf&srt=sco&spr=https%2Chttp&st=2025-01-06T14%3A53%3A30Z&se=2035-01-07T14%3A53%3A00Z&sp=rwdftlacup&sig=jclETGilOzONYp4Y0iK9SpVRLGyehaS5lg5booJ9VYA%3D&restype=container"; then
            break
            fi
            sleep 1
        done
        '
