# Codespell configuration is within .codespellrc
---
name: Codespell

on:
  push:
    branches: [main, 'support/**']
  pull_request:
    branches: [main, 'support/**']

permissions:
  contents: read

jobs:
  codespell:
    name: Check for spelling errors
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Annotate locations with typos
        uses: codespell-project/codespell-problem-matcher@v1.2.0
      - name: Codespell
        uses: codespell-project/actions-codespell@v2
